version: '3'
services:
  db:
    image: postgres:14.2-alpine
    ports:
      - '5432:5432'
    volumes:
      - .postgres:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: secret
    tty: true
    stdin_open: true
  app:
    build:
      context: ./app
      dockerfile: containers/development/Dockerfile
    # command: /bin/bash -c "source ~/.cargo/env && mix deps.get && iex -S mix phx.server"
    command: /bin/bash -c "mix deps.get && iex -S mix phx.server"
    ports:
      - '4000:4000'
    volumes:
      - ./app:/app
    environment:
      - DOCKER_POSTGRES_HOST=db
      - ERL_AFLAGS=-kernel shell_history enabled
    depends_on:
      - db
    tty: true
    stdin_open: true
  web:
    build:
      context: ./web
      dockerfile: containers/development/Dockerfile
    # command: /bin/sh -c "./scripts/create_fcm_sw; yarn install && yarn serve"
    command: /bin/sh -c "yarn install && yarn serve"
    ports:
      - '8080:8080'
      - '24678:24678'
    volumes:
      - ./web:/app
      - /app/node_modules
